name: Format code

on:
  push:
    branches:
      - master

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install PHP CS Fixer
        run: composer global require friendsofphp/php-cs-fixer

      - name: Cache PHP CS Fixer
        uses: actions/cache@v1
        with:
          path: ~/.composer/vendor/bin
          key: composer-php-cs-fixer-${{ hashFiles('~/.composer/composer.lock') }}

      - name: Fix code style
        run: ~/.composer/vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --show-progress=estimating
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
